language: python
python:
- '2.7'
install:
- npm install
script: py.test
env:
  global:
  - secure: HDaMwy2GZTN6p2sE30yzdEAws4qHiUbRqXn1Bi5tzZ4La8FzTPn8uyay1bVpjxMmngl3d/0oA2G5/qvgjsfkcHkShxYDYF1l1q6VgDdsRnFpnE2AMn6b6llZcJXWZXgBX+Vs4I/ScWtb3DQ09hJqjIu895xMje75xx1K0Sw4yQs=
after_success:
- npm install
- gulp pack
- git remote set-url origin "https://${GH_TOKEN}@github.com/rkuykendall/project-rome-js.git"
- git config --global user.email "robert@rkuykendall.com"
- git config --global user.name "Travis-CI"
- gulp deploy
sudo: false
